### ISSUE TITLE
add steps on how you got it working

### ISSUE THREAD

**Issue by sathishvj** [rodrigoreal/ionic2-angularfire-login#2]
Could you please add in the README the steps to get it working?  i.e. which files you had to edit, which all you had to `npm install`, what you had to check for after, etc.?

p.s. in any case this is a useful project and I've reposted it.

**Comment by rodrigoreal** [comment]
@sathishvj you just need to to a `npm install` and it will work.

and if you want to use this project as a start point you will also need to change this part of the code below in `app.ts` otherwise you will be using mine.

```
defaultFirebase({
    apiKey: "<your-key>",
    authDomain: "<your-project-authdomain>",
    databaseURL: "<your-database-URL>",
    storageBucket: "<your-storage-bucket>",
  })
```

**Comment by sathishvj** [comment]
You're seeing it from the point of somebody cloning your entire project.  But most people are likely to start off with `ionic new` and then integrate the pieces they want.  So what would be useful is how you got to this stage.

**Comment by rodrigoreal** [comment]
@sathishvj ok, i understand now your point of view, i'll update the README as soon as i can.

**Comment by rodrigoreal** [comment]
@sathishvj ive added these steps in the README as you asked.
[Installation & Setup](https://github.com/rodrigoreal/ionic2-angularfire-login/blob/master/docs/install-and-setup-in-your-own-project.md)

**Comment by MauricioKruijer** [comment]
@rodrigoreal thanks for updating the readme, I will try to use these steps in a dummy project. 
When I follow the current steps I only get a blank page what am I missing here?

I get the following errors while running `ionic serve` not sure if thats why I'm getting a blank page..

```
node_modules/angularfire2/providers/auth.d.ts(12,20): Error TS1112: A class member cannot be declared optional.
node_modules/angularfire2/utils/firebase_object_observable.d.ts(6,17): Error TS1112: A class member cannot be declared optional.
```

![question](https://cloud.githubusercontent.com/assets/224625/16981646/ce23eb9e-4e6b-11e6-85e4-c2784bcd72cb.gif)

**Comment by sathishvj** [comment]
@MauricioKruijer Can you start a new empty project with `ionic start testproject --v2` and see if you are getting the same error?  

From the errors it looks it is in the libraries and that is unlikely.  You could delete the node_modules directory and do npm install again.

p.s. Meanwhile, what tool are you using to do the gif recording and conversion?

**Comment by MauricioKruijer** [comment]
@sathishvj Creating a new blank project worked fine, removing node_modules and nam install again didn't work. 

p.s. I use http://www.cockos.com/licecap/ and it works great haha

**Comment by sathishvj** [comment]
Are the package.json dependencies in both the projects the same?  If they aren't, you can update the one that is not working.

**Comment by MauricioKruijer** [comment]
The new project is using ionic beta 10 and some other deps on angular2. When I use those in this project's package.json (remove node_modules and run npm install again) the same errors (`Error TS1112: A class member cannot be declared optional`) show up and the page still stays blank in my browser.

**Comment by harpreet2602** [comment]
I am also getting the same error after cloning the project and npm install

**Comment by rodrigoreal** [comment]
I'm also getting both these errors, but they are from the angularfire module, it will probably be fixed in the next release, but the project is working.
That is not the cause of you getting a blank page.

@harpreet2602 are you getting also a blank page?

**Comment by MauricioKruijer** [comment]
I have solved the issue, turns out you have to add your IP ( I don't know how to bind `ionic serve` to localhost >_<) to your firebase app.

I have changed my api keys to my own and added my local IP to firebase at the Auth section and scroll down.

<img width="976" alt="screen shot 2016-07-20 at 12 38 27" src="https://cloud.githubusercontent.com/assets/224625/16983826/116b26b4-4e77-11e6-80bb-b0cfcc33a5a0.png">

**Comment by rodrigoreal** [comment]
@MauricioKruijer oh, thats it, i use localhost as default so i never had this problem before, you can change to localhost by following these instructions.

There is a file called `ionic.config` which you can modify with this setting. On Mac this file is at `~/.ionic`. On a PC it can be found at `c:/users/username/.ionic`. Inside you'll see something like this which you can edit the ionicServeAddress value.

``` bash
{
  "lastVersionChecked": "2.0.0-beta.32",
  "ionicServeAddress": "localhost",
  "ank": "..."
}
```

**Comment by MauricioKruijer** [comment]
Thanks @rodrigoreal I have changed it to localhost. I still get the blank page on mobile however :( 

```
[24183:1062938] EXCEPTION: Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https.
2016-07-20 13:41:33.710 ionic2-angularfire2-login-example[24183:1062938] ERROR: EXCEPTION: Error: This operation is not supported in the environment this application is running on. "location.protocol" must be http or https.
```

**Comment by rodrigoreal** [comment]
@MauricioKruijer oh, that is strange, ill have a look into that as soon as i can

**Comment by harpreet2602** [comment]
update to angularfire2@2.0.0-beta.3-0930330, blank page issue will go away

**Comment by harpreet2602** [comment]
@MauricioKruijer : The blank page issue will get resolved with angularfire update to angularfire2@2.0.0-beta.3-0930330 but the facebook authentication will not work on mobile/simulator... you will get the below error:
Error: This operation is not supported in the environment this application is running on.
"location.protocol" must be http or https.

Refer: https://github.com/rodrigoreal/ionic2-angularfire-login/issues/4

**Comment by MauricioKruijer** [comment]
@harpreet2602 Thanks! Email signup/login is working after `npm install angularfire2@2.0.0-beta.3-0930330`. Facebook/google auth it not working as you mentioned, will try out the code provided in #4

**Comment by rodrigoreal** [comment]
I'm closing this issue because it has already been implemented.
